# Generated by Django 5.2.17 on 2026-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_diagnosis_result_fields_careguide_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='careguide',
            name='guide_type',
            field=models.CharField(choices=[('BASIC', '기본 관리'), ('POST_PURCHASE', '구매 직후 관리'), ('AFTER_CARE', '사후 케어')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='visitreservation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitreservation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='condition_level',
            field=models.CharField(blank=True, choices=[('SAFE', '안전'), ('CAUTION', '주의'), ('DANGER', '위험')], max_length=10),
        ),
    ]
