# Generated by Django 5.2.17 on 2026-08-15 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_careguide_guide_type_visitreservation_contact_name_and_more'),
        ('catalog', '0003_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='catalog.product'),
        ),
    ]
