# Generated by Django 5.2.17 on 2026-08-16 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_alter_servicerequest_product'),
        ('catalog', '0004_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreservation',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_reservations', to='care.diagnosis'),
        ),
        migrations.AddConstraint(
            model_name='visitreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RESERVED')), fields=('store', 'visit_at'), name='unique_active_store_visit_slot'),
        ),
    ]
