# Generated by Django 5.2.12 on 2026-08-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_visitreservation_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='store',
            name='channel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='official_store_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='sigungu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
