# Generated by Django 5.2.17 on 2026-09-12 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_alter_store_options_store_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='analysis_attempts',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='analysis_revision',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='completed_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='lease_expires_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='lease_token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
