# Generated by Django 5.2.17 on 2026-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_passport_purchase_image_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_channel',
            field=models.CharField(blank=True, choices=[('ONLINE', '온라인'), ('OFFLINE', '오프라인')], max_length=10),
        ),
    ]
